## Avances Laboratorio #2 
##### Data Science  -  Universidad del Valle de Guatemala

- Gustavo Andres Gonzalez Pineda 21438
- Maria Marta Ramirez Gil 21342

---------------------------------------------------------------------------------------

### Vista preliminar de los datasets

In [1]:
# Imports
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from IPython.display import display

# Cargar los datos CONSUMO
consumo_df = pd.read_csv('data/Consumo.csv', header=6)
# eliminar las primeras 5 filas y dejar como encabezado la sexta fila
consumo_df = consumo_df[5:] 

print("CONSUMO DF")
display(consumo_df)
print("\n")
print("CONSUMO DF COLUMNAS")
print(consumo_df.columns)
print("\n")
print("CONSUMO DF TIPOS DE DATOS")
print(consumo_df.dtypes)

CONSUMO DF

,Fecha,Aceites lubricantes,Asfalto,Bunker,Ceras,Combustible turbo jet,Diesel bajo azufre,Diesel ultra bajo azufre,Gas licuado de petróleo,Gasolina de aviación,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
5,Jun/2000,0.00,"40,623.00","404,033.69",0.00,0.00,0.00,0.00,"196,321.93","1,641.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Jul/2000,0.00,"36,670.00","291,436.20",0.00,0.00,0.00,0.00,"192,344.50","1,598.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Aug/2000,0.00,"25,033.00","373,811.63",0.00,0.00,0.00,0.00,"203,727.08","1,438.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sep/2000,0.00,"16,906.00","322,718.89",0.00,0.00,0.00,0.00,"194,565.10","1,469.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Oct/2000,0.00,"22,070.00","260,955.42",0.00,0.00,0.00,0.00,"210,261.83","1,475.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,Apr/2024,"30,759.23","12,942.60","169,259.07",-408.66,"84,078.82","1,428,143.44","13,960.16","531,880.19","1,495.49",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,May/2024,"27,925.45","10,648.82","407,622.36",-679.88,"88,754.57","1,401,052.37","11,513.25","536,754.38","1,605.58",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,Fuente: informes mensuales de titulares de lic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,Nota: Información sujeta a actualización por p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

CONSUMO DF COLUMNAS
Index(['Fecha', 'Aceites lubricantes', 'Asfalto', 'Bunker', 'Ceras',
       'Combustible turbo jet', 'Diesel bajo azufre',
       'Diesel ultra bajo azufre', 'Gas licuado de petróleo',
       'Gasolina de aviación', 'Gasolina regular', 'Gasolina superior',
       'Grasas lubricantes', 'Kerosina', 'Mezclas\noleosas', 'Naftas',
       'PetCoke', 'Petróleo crudo', 'Solventes', 'Butano',
       'Diesel alto azufre', 'Orimulsión', 'Total', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51',
       'Unnamed: 52'],
      dtype='object')


CONSUMO DF TIPOS DE DATOS
Fecha                        object
Aceites lubricantes          object
Asfalto                      object
Bunker                       object
Ceras                       float64
Combustible turbo jet        object
Diesel bajo azufre           object
Diesel ultra bajo azufre     object
Gas licuado de petróleo      object
Gasolina de aviación         object
Gasolina regular             object
Gasolina superior            object
Grasas lubricantes           object
Kerosina                     object
Mezclas\noleosas             object
Naftas                      float64
PetCoke                      object
Petróleo crudo               object
Solventes                    object
Butano                      float64
Diesel alto azufre           object
Orimulsión                   object
Total                        object
Unnamed: 23                 float64
Unnamed: 24                 float64
Unnamed: 25                 float64
Unnamed: 26                 float64
Unnamed: 27                 float64
Unnamed: 28                 float64
Unnamed: 29                 float64
Unnamed: 30                 float64
Unnamed: 31                 float64
Unnamed: 32                 float64
Unnamed: 33                 float64
Unnamed: 34                 float64
Unnamed: 35                 float64
Unnamed: 36                 float64
Unnamed: 37                 float64
Unnamed: 38                 float64
Unnamed: 39                 float64
Unnamed: 40                 float64
Unnamed: 41                 float64
Unnamed: 42                 float64
Unnamed: 43                 float64
Unnamed: 44                 float64
Unnamed: 45                 float64
Unnamed: 46                 float64
Unnamed: 47                 float64
Unnamed: 48                 float64
Unnamed: 49                 float64
Unnamed: 50                 float64
Unnamed: 51                 float64
Unnamed: 52                 float64
dtype: object

#### Observaciones
- Tiene columnas que no contienen nada.
- Tiene filas que no contienen nada.
- Solo usar regular, super, diesel y gas licuado

In [2]:
# Cargar los datos IMPORTACION
importacion_df = pd.read_csv('data/Importacion.csv', header=6)
importacion_df = importacion_df[5:]

print("IMPORTACION DF")
display(importacion_df)
print("\n")
print("IMPORTACION DF COLUMNAS")
print(importacion_df.columns)
print("\n")
print("IMPORTACION DF TIPOS DE DATOS")
print(importacion_df.dtypes)

IMPORTACION DF

,Fecha,Aceites lubricantes,Asfalto,Bunker,Ceras,Combustible turbo jet,Diesel bajo azufre,Diesel ultra bajo azufre,Gas licuado de petróleo,Gasolina de aviación,...,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68
5,Jun/2001,0.00,"6,229.04","218,765.60",0.00,0.00,0.00,0.00,"190,004.42",492.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Jul/2001,0.00,"3,103.99","156,109.00",0.00,0.00,0.00,0.00,"206,022.83",655.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Aug/2001,0.00,"27,821.06","189,692.60",0.00,0.00,0.00,0.00,"100,561.47",607.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sep/2001,0.00,"2,324.85","385,142.30",0.00,0.00,0.00,0.00,"186,839.02","3,868.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Oct/2001,0.00,"1,484.40","214,138.00",0.00,0.00,0.00,0.00,"163,864.20",650.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,Apr/2024,"37,444.60","7,990.99","77,253.65",33.52,"85,752.17","1,294,706.12",0.00,"473,940.66","3,351.23",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,May/2024,"31,035.55","10,483.78","544,682.15",91.83,"94,606.00","1,470,870.09",0.00,"684,864.46",0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,Fuente: informes mensuales de titulares de lic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,Nota: Información sujeta a actualización por p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

IMPORTACION DF COLUMNAS
Index(['Fecha', 'Aceites lubricantes', 'Asfalto ', 'Bunker', 'Ceras',
       'Combustible turbo jet', 'Diesel bajo azufre',
       'Diesel ultra bajo azufre', 'Gas licuado de petróleo',
       'Gasolina de aviación', 'Gasolina regular', 'Gasolina superior',
       'Grasas lubricantes', 'Kerosina', 'Mezclas oleosas', 'Naftas',
       'Petcoke', 'Petróleo crudo', 'Solventes', 'Butano',
       'Diesel alto azufre', 'MTBE', 'Orimulsión', 'Petróleo reconstituido',
       'Total importación', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51',
       'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55',
       'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59',
       'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63',
       'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67',
       'Unnamed: 68'],
      dtype='object')


IMPORTACION DF TIPOS DE DATOS
Fecha                   object
Aceites lubricantes     object
Asfalto                 object
Bunker                  object
Ceras                  float64
                        ...
Unnamed: 64            float64
Unnamed: 65            float64
Unnamed: 66            float64
Unnamed: 67            float64
Unnamed: 68            float64
Length: 69, dtype: object

#### Observaciones
- Solo usar regular, super, diesel y gas licuado
- Tiene columnas que no contienen nada.
- Tiene filas que no contienen nada.

In [3]:
# Cargar los datos PRECIOS
precios_df = pd.read_csv('data/Precios.csv', header=7)
precios_df = precios_df[6:]

print("PRECIOS DF")
display(precios_df)
print("\n")
print("PRECIOS DF COLUMNAS")
print(precios_df.columns)
print("\n")
print("PRECIOS DF TIPOS DE DATOS")
print(precios_df.dtypes)

PRECIOS DF

,FECHA,Tipo de Cambio,Superior,Regular,Diesel,Bunker,Glp Cilindro 25Lbs.,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
6,06/Jan/2024,7.82322,30.47,28.97,29.48,18.99,115.00,4.60,NaN,NaN,NaN,NaN
7,07/Jan/2024,7.82322,30.47,28.97,29.48,18.99,115.00,4.60,NaN,NaN,NaN,NaN
8,08/Jan/2024,7.81941,30.47,28.97,29.48,18.99,115.00,4.60,NaN,NaN,NaN,NaN
9,09/Jan/2024,7.81686,30.47,28.97,29.48,18.99,115.00,4.60,NaN,NaN,NaN,NaN
10,10/Jan/2024,7.82016,30.47,28.97,29.48,18.99,115.00,4.60,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,Fuente precios nacionales: Sección Comercializ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,Fuente tipo de cambio: Banco de Guatemala.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

PRECIOS DF COLUMNAS
Index(['FECHA', 'Tipo de Cambio', 'Superior', 'Regular', 'Diesel', 'Bunker',
       'Glp Cilindro 25Lbs.', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')


PRECIOS DF TIPOS DE DATOS
FECHA                   object
Tipo de Cambio          object
Superior                object
Regular                 object
Diesel                  object
Bunker                  object
Glp Cilindro 25Lbs.     object
Unnamed: 7              object
Unnamed: 8             float64
Unnamed: 9             float64
Unnamed: 10            float64
Unnamed: 11            float64
dtype: object

#### Observaciones
- Solo usar las columnas regular, super, diesel y gas licuado.
- Columnas vacias.
- Filas vacias.

### Limpieza de los datasets